background #202020
foreground #dfdfdf

color0  #404040
color1  #ff8080
color2  #80ff80
color3  #ffff80
color4  #8080ff
color5  #ff80ff
color6  #80ffff
color7  #bfbfbf

color8  #000000
color9  #ff0000
color10 #00ff00
color11 #ffff00
color12 #0000ff
color13 #ff00ff
color14 #00ffff
color15 #ffffff

font_family      family="RobotoMono Nerd Font" style=Bold
bold_font        family="RobotoMono Nerd Font" style=Bold
italic_font      family="RobotoMono Nerd Font" style=Bold
bold_italic_font family="RobotoMono Nerd Font" style=Bold

font_size 10.5

window_padding_width 13
