backend = "glx";
vsync = true;

shadow = true;
shadow-color = "#808080";
shadow-radius = 2;
shadow-offset-x = -2;
shadow-offset-y = -2;

rules: ({
  match = "override_redirect = true";
  shadow = false;
})
