backend = "xrender";
vsync = true;
shadow = true;

shadow-radius = 8;
shadow-opacity = 0.5;
shadow-offset-x = -8;
shadow-offset-y = -8;

rules: ({
  match = "override_redirect = true";
  shadow = false;
})
