backend = "xrender";
vsync = true;
shadow = false;

rules: (
  {
    match = "class_g = 'Xdg-desktop-portal-gtk'";
    shadow = true;
  },
  {
    match = "override_redirect = true";
    shadow = false;
  }
)
